<?php

// $Id: v 1.00 2004/12/30 Gustavo S. Villa Exp
//  ------------------------------------------------------------------------ //
//                            e-Notícias                                     //
//                              E-WARE                                       //
//                   <http://www.e-ware.com.br>                             //
//  ------------------------------------------------------------------------ //
//  Você não pode substituir ou alterar qualquer parte desses comentários    //
//  ou créditos dos titulares e autores os quais são considerados direitos   //
//  reservados.                                                              //
//  ------------------------------------------------------------------------ //
//  Autor: Gustavo S. Villa  <guvilladev@e-ware.com.br>                      //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _MI_eNoticias_MD_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _MI_eNoticias_MD_DESC;
$modversion['author'] = 'Gustavo S. Villa';
$modversion['credits'] = 'Catzwolf';
$modversion['help'] = 'help/index.html';
$modversion['license'] = 'GPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/eNoticias.gif';
$modversion['dirname'] = 'eNoticias';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'eNoticias_Colunas';
$modversion['tables'][1] = 'eNoticias_Artigos';
$modversion['tables'][2] = 'eNoticias_Votacoes';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'eNoticias_search';

// Menu
$modversion['hasMain'] = 1;
/*
global $xoopsModuleConfig, $xoopsDB, $xoopsUser, $xoopsUser, $xoopsConfig, $myts, $xoopsModule;

$user = '';

if (!empty($xoopsUser))
    {
    $user = $xoopsUser->getVar('uid');
    }
$query = $xoopsDB -> query ( "SELECT author FROM " . $xoopsDB -> prefix ("eNoticias_Colunas") . " WHERE author = $user ");
$isauthor = $xoopsDB -> getRowsNum($query);

if (!empty($xoopsUser) && is_object($xoopsModule))
    {
    if ( $xoopsUser -> isAdmin($xoopsModule -> getVar('mid')) || $isauthor == 1 )
        {
        $modversion['sub'][1]['name'] = _MI_eNoticias_SUB_SMNAME1;
        $modversion['sub'][1]['url'] = "submit.php?op=add";
        }
    }
unset ($isauthor);

$groups = ( $xoopsUser ) ? $xoopsUser -> getGroups() : XOOPS_GROUP_ANONYMOUS;

$gpermHandler =  xoops_getHandler( 'groupperm' );

$sql = $xoopsDB->query( "SELECT columnID, name FROM " . $xoopsDB->prefix( "eNoticias_Colunas" ) . " " );
$i = 2;

$hModConfig = xoops_getHandler('config');
$hModule = xoops_getHandler('module');
if ($noticiaModule =& $hModule->getByDirname('eNoticias'))
{
    $module_id = $noticiaModule -> getVar( 'mid' );
    $noticiaConfig =& $hModConfig->getConfigsByCat(0, $noticiaModule->getVar('mid'));
    if ( isset($noticiaConfig['colsinmenu']) && $noticiaConfig['colsinmenu'] == 1 && is_object( $xoopsUser ) )
    {
    while ( list( $columnID, $name ) = $xoopsDB->fetchRow( $sql ) )
        {
        if ( $gpermHandler -> checkRight( 'Column Permissions', $columnID, $groups, $module_id ) )
            {
            $modversion['sub'][$i]['name'] = $name;
            $modversion['sub'][$i]['url'] = "column.php?columnID=" . $columnID . "";
            $i++;
            }
        }
    }
}
*/

$modversion['blocks'][1]['file'] = 'enot_rated.php';
$modversion['blocks'][1]['name'] = _MI_eNoticias_enotRATED;
$modversion['blocks'][1]['description'] = 'Shows best rated articles';
$modversion['blocks'][1]['show_func'] = 'b_enot_rated';
$modversion['blocks'][1]['edit_func'] = 'b_enot_rated_edit';
$modversion['blocks'][1]['options'] = 'rating|5|65';
$modversion['blocks'][1]['template'] = 'enot_rated.html';

$modversion['blocks'][2]['file'] = 'enot_new.php';
$modversion['blocks'][2]['name'] = _MI_eNoticias_enotNEW;
$modversion['blocks'][2]['description'] = 'Shows new articles';
$modversion['blocks'][2]['show_func'] = 'b_enot_new_show';
$modversion['blocks'][2]['edit_func'] = 'b_enot_new_edit';
$modversion['blocks'][2]['options'] = 'datesub|5|65';
$modversion['blocks'][2]['template'] = 'enot_new.html';

$modversion['blocks'][3]['file'] = 'enot_top.php';
$modversion['blocks'][3]['name'] = _MI_eNoticias_enotTOP;
$modversion['blocks'][3]['description'] = 'Shows popular articles';
$modversion['blocks'][3]['show_func'] = 'b_enot_top_show';
$modversion['blocks'][3]['edit_func'] = 'b_enot_top_edit';
$modversion['blocks'][3]['options'] = 'counter|5|65';
$modversion['blocks'][3]['template'] = 'enot_top.html';

$modversion['blocks'][4]['file'] = 'enot_spot.php';
$modversion['blocks'][4]['name'] = 'Destaques';
$modversion['blocks'][4]['description'] = 'Shows latest articles in a column';
$modversion['blocks'][4]['show_func'] = 'b_enot_spot_show';
$modversion['blocks'][4]['edit_func'] = 'b_enot_spot_edit';
$modversion['blocks'][4]['options'] = '1|5|0|0|0|ver|0';
$modversion['blocks'][4]['template'] = 'enot_spot.html';

$modversion['blocks'][5]['file'] = 'enot_list.php';
$modversion['blocks'][5]['name'] = 'Colunistas';
$modversion['blocks'][5]['description'] = 'Exibe os colunistas e a última coluna publicada';
$modversion['blocks'][5]['show_func'] = 'b_enot_list_show';
$modversion['blocks'][5]['template'] = 'enot_list.html';

$modversion['blocks'][6]['file'] = 'enot_destaque01.php';
$modversion['blocks'][6]['name'] = 'Esportes';
$modversion['blocks'][6]['description'] = 'Exibe a última notícia da categoria de esportes, como destaque';
$modversion['blocks'][6]['show_func'] = 'b_enot_destaque01_show';
$modversion['blocks'][6]['template'] = 'enot_destaque01.html';

$modversion['blocks'][7]['file'] = 'enot_destaque02.php';
$modversion['blocks'][7]['name'] = 'Notícias';
$modversion['blocks'][7]['description'] = 'Exibe a última notícia da categoria geral como destaque';
$modversion['blocks'][7]['show_func'] = 'b_enot_destaque02_show';
$modversion['blocks'][7]['template'] = 'enot_destaque02.html';

// Templates
$modversion['templates'][1]['file'] = 'eNoticias_column.html';
$modversion['templates'][1]['description'] = 'Display columns';
$modversion['templates'][2]['file'] = 'eNoticias_index.html';
$modversion['templates'][2]['description'] = 'Display index';
$modversion['templates'][3]['file'] = 'eNoticias_article.html';
$modversion['templates'][3]['description'] = 'Display article';

// Config Settings (only for modules that need config settings generated automatically)
$modversion['config'][1]['name'] = 'allowsubmit';
$modversion['config'][1]['title'] = '_MI_eNoticias_ALLOWSUBMIT';
$modversion['config'][1]['description'] = '_MI_eNoticias_ALLOWSUBMITDSC';
$modversion['config'][1]['formtype'] = 'yesno';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 1;

$modversion['config'][2]['name'] = 'autoapprove';
$modversion['config'][2]['title'] = '_MI_eNoticias_AUTOAPPROVE';
$modversion['config'][2]['description'] = '_MI_eNoticias_AUTOAPPROVEDSC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 0;

$modversion['config'][3]['name'] = 'adminhits';
$modversion['config'][3]['title'] = '_MI_eNoticias_ALLOWADMINHITS';
$modversion['config'][3]['description'] = '_MI_eNoticias_ALLOWADMINHITSDSC';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;

$modversion['config'][4]['name'] = 'perpage';
$modversion['config'][4]['title'] = '_MI_eNoticias_PERPAGE';
$modversion['config'][4]['description'] = '_MI_eNoticias_PERPAGEDSC';
$modversion['config'][4]['formtype'] = 'select';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 5;
$modversion['config'][4]['options'] = ['5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50];

$modversion['config'][5]['name'] = 'indexperpage';
$modversion['config'][5]['title'] = '_MI_eNoticias_PERPAGEINDEX';
$modversion['config'][5]['description'] = '_MI_eNoticias_PERPAGEINDEXDSC';
$modversion['config'][5]['formtype'] = 'select';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 5;
$modversion['config'][5]['options'] = ['5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50];

$modversion['config'][6]['name'] = 'sbimgdir';
$modversion['config'][6]['title'] = '_MI_eNoticias_IMGDIR';
$modversion['config'][6]['description'] = '_MI_eNoticias_IMGDIRDSC';
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'text';
$modversion['config'][6]['default'] = 'modules/eNoticias/images';

$modversion['config'][7]['name'] = 'sbuploaddir';
$modversion['config'][7]['title'] = '_MI_eNoticias_UPLOADDIR';
$modversion['config'][7]['description'] = '_MI_eNoticias_UPLOADDIRDSC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'text';
$modversion['config'][7]['default'] = 'modules/eNoticias/images/uploads';

$modversion['config'][8]['name'] = 'maximgwidth';
$modversion['config'][8]['title'] = '_MI_eNoticias_IMGWIDTH';
$modversion['config'][8]['description'] = '_MI_eNoticias_IMGWIDTHDSC';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 800;

$modversion['config'][9]['name'] = 'maximgheight';
$modversion['config'][9]['title'] = '_MI_eNoticias_IMGHEIGHT';
$modversion['config'][9]['description'] = '_MI_eNoticias_IMGHEIGHTDSC';
$modversion['config'][9]['formtype'] = 'textbox';
$modversion['config'][9]['valuetype'] = 'int';
$modversion['config'][9]['default'] = 800;

$modversion['config'][10]['name'] = 'maxfilesize';
$modversion['config'][10]['title'] = '_MI_eNoticias_MAXFILESIZE';
$modversion['config'][10]['description'] = '_MI_eNoticias_MAXFILESIZEDSC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 250000;

$modversion['config'][11]['name'] = 'dateformat';
$modversion['config'][11]['title'] = '_MI_eNoticias_DATEFORMAT';
$modversion['config'][11]['description'] = '_MI_eNoticias_DATEFORMATDSC';
$modversion['config'][11]['formtype'] = 'textbox';
$modversion['config'][11]['valuetype'] = 'text';
$modversion['config'][11]['default'] = 'd-M-Y H:i';

$modversion['config'][12]['name'] = 'globaldisplaycomments';
$modversion['config'][12]['title'] = '_MI_eNoticias_ALLOWCOMMENTS';
$modversion['config'][12]['description'] = '_MI_eNoticias_ALLOWCOMMENTSDSC';
$modversion['config'][12]['formtype'] = 'yesno';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 1;

$modversion['config'][13]['name'] = 'morearts';
$modversion['config'][13]['title'] = '_MI_eNoticias_MOREARTS';
$modversion['config'][13]['description'] = '_MI_eNoticias_MOREARTSDSC';
$modversion['config'][13]['formtype'] = 'select';
$modversion['config'][13]['valuetype'] = 'int';
$modversion['config'][13]['default'] = 3;
$modversion['config'][13]['options'] = ['3' => 3, '5' => 5, '10' => 10, '15' => 15, '20' => 20];

$modversion['config'][14]['name'] = 'colsinmenu';
$modversion['config'][14]['title'] = '_MI_eNoticias_COLSINMENU';
$modversion['config'][14]['description'] = '_MI_eNoticias_COLSINMENUDSC';
$modversion['config'][14]['formtype'] = 'yesno';
$modversion['config'][14]['valuetype'] = 'int';
$modversion['config'][14]['default'] = 0;

$modversion['config'][15]['name'] = 'colsperindex';
$modversion['config'][15]['title'] = '_MI_eNoticias_COLSPERINDEX';
$modversion['config'][15]['description'] = '_MI_eNoticias_COLSPERINDEXDSC';
$modversion['config'][15]['formtype'] = 'select';
$modversion['config'][15]['valuetype'] = 'int';
$modversion['config'][15]['default'] = 3;
$modversion['config'][15]['options'] = ['3' => 3, '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50];

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'articleID';
$modversion['comments']['pageName'] = 'article.php';

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'eNoticias_com_approve';
$modversion['comments']['callback']['update'] = 'eNoticias_com_update';

// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'eNoticias_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_eNoticias_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_eNoticias_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = ['index.php', 'article.php'];

$modversion['notification']['category'][2]['name'] = 'column';
$modversion['notification']['category'][2]['title'] = _MI_eNoticias_COLUMN_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_eNoticias_COLUMN_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = ['index.php'];
$modversion['notification']['category'][2]['item_name'] = 'columnID';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['category'][3]['name'] = 'article';
$modversion['notification']['category'][3]['title'] = _MI_eNoticias_ARTICLE_NOTIFY;
$modversion['notification']['category'][3]['description'] = _MI_eNoticias_ARTICLE_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = 'article.php';
$modversion['notification']['category'][3]['item_name'] = 'articleID';
$modversion['notification']['category'][3]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name'] = 'new_column';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_eNoticias_GLOBAL_NEWCOLUMN_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_eNoticias_GLOBAL_NEWCOLUMN_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_eNoticias_GLOBAL_NEWCOLUMN_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newcolumn_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_eNoticias_GLOBAL_NEWCOLUMN_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'article_submit';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['admin_only'] = 1;
$modversion['notification']['event'][2]['title'] = _MI_eNoticias_GLOBAL_ARTICLESUBMIT_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_eNoticias_GLOBAL_ARTICLESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_eNoticias_GLOBAL_ARTICLESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_articlesubmit_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_eNoticias_GLOBAL_ARTICLESUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][3]['name'] = 'new_article';
$modversion['notification']['event'][3]['category'] = 'global';
$modversion['notification']['event'][3]['title'] = _MI_eNoticias_GLOBAL_NEWARTICLE_NOTIFY;
$modversion['notification']['event'][3]['caption'] = _MI_eNoticias_GLOBAL_NEWARTICLE_NOTIFYCAP;
$modversion['notification']['event'][3]['description'] = _MI_eNoticias_GLOBAL_NEWARTICLE_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_newarticle_notify';
$modversion['notification']['event'][3]['mail_subject'] = _MI_eNoticias_GLOBAL_NEWARTICLE_NOTIFYSBJ;

$modversion['notification']['event'][4]['name'] = 'article_submit';
$modversion['notification']['event'][4]['category'] = 'column';
$modversion['notification']['event'][4]['admin_only'] = 1;
$modversion['notification']['event'][4]['title'] = _MI_eNoticias_COLUMN_ARTICLESUBMIT_NOTIFY;
$modversion['notification']['event'][4]['caption'] = _MI_eNoticias_COLUMN_ARTICLESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][4]['description'] = _MI_eNoticias_COLUMN_ARTICLESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = 'column_articlesubmit_notify';
$modversion['notification']['event'][4]['mail_subject'] = _MI_eNoticias_COLUMN_ARTICLESUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][5]['name'] = 'new_article';
$modversion['notification']['event'][5]['category'] = 'column';
$modversion['notification']['event'][5]['title'] = _MI_eNoticias_COLUMN_NEWARTICLE_NOTIFY;
$modversion['notification']['event'][5]['caption'] = _MI_eNoticias_COLUMN_NEWARTICLE_NOTIFYCAP;
$modversion['notification']['event'][5]['description'] = _MI_eNoticias_COLUMN_NEWARTICLE_NOTIFYDSC;
$modversion['notification']['event'][5]['mail_template'] = 'column_newarticle_notify';
$modversion['notification']['event'][5]['mail_subject'] = _MI_eNoticias_COLUMN_NEWARTICLE_NOTIFYSBJ;

$modversion['notification']['event'][6]['name'] = 'approve';
$modversion['notification']['event'][6]['category'] = 'article';
$modversion['notification']['event'][6]['invisible'] = 1;
$modversion['notification']['event'][6]['title'] = _MI_eNoticias_ARTICLE_APPROVE_NOTIFY;
$modversion['notification']['event'][6]['caption'] = _MI_eNoticias_ARTICLE_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][6]['description'] = _MI_eNoticias_ARTICLE_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][6]['mail_template'] = 'article_approve_notify';
$modversion['notification']['event'][6]['mail_subject'] = _MI_eNoticias_ARTICLE_APPROVE_NOTIFYSBJ;
